### ISSUE TITLE
Use json-server to mock data

### ISSUE THREAD

**Issue by oscargm** [oscargm/air-quality-checker#1]
change hard coded data in model for [json-server](https://github.com/typicode/json-server)

**Comment by elboletaire** [comment]
Just a question about this. The current data is using json-server but, it's still hardcoded, right?

**Comment by oscargm** [comment]
Yes, still hardcoded data but has been extracted from the server requests

**Comment by elboletaire** [comment]
Why you think so? AFAIK, the Generalitat de Catalunya is always a step forward in these things, at least compared to other governments...

BTW, how do you extract the information manually from there? You could easily do a scrapper using gulp or whatever else.

**Comment by oscargm** [comment]
Yes, gencat is step forward in opening data, but if you dig in, you'll see that there is no data related to air quality, neither current data or historic data. I found that diputació de Barcelona had data related to air quality [here](https://dadesobertes.diba.cat/datasets/qualitat-de-laire-xarxa-de-particules), and I asked for more, at fist they answered me that they would dig in in territori's department but this week I got the answer and they refer to idescat, [here](https://www.idescat.cat/pub/?id=aec&n=237) and [here](https://www.idescat.cat/pub/?id=aec&n=238) for historical data.

but these readings are far away from what I can get from [here](http://dtes.gencat.cat/icqa/). where they have automated data (with 3-4h delay but still, is more or less current data), from a lot more polluters than the other sources. I asked to the page email for opening the api data, even though i know that they will say no.

I got the data navigating through the web and catching the answers from their server. Even though i know scrapping would be a fair solution, I think this should be a public API, and I'll try with all my efforts

**Comment by oscargm** [comment]
Yes, i thought so, it'd be a big effort for me, if anyone wants to do it, for me it's good as it gets the data, but at least I want to try to knock all the doors, and face them that this is important data, and their platform is shitty from an ux point.

I have some ideas for treating the data, p.e. I would like to match special dates for Barcelona like 23/04 (full traffic) or 01/11 (less traffic) or football match days for showing how traffic impacts on pollution in certain areas of the city. 

I hope i get the api and I can focus on these things instead of scrapping.

Funny the catalan words thing, I preffer to keep that in english so anyone can use it in the future :wink:
